### ISSUE TITLE
Clean up update using with

### ISSUE THREAD

**Issue by haslinger** [PanoptikumIO/pan#8]
use [Learning Elixir's with](http://learningelixir.joekain.com/learning-elixir-with/) as a guideline

**Comment by optikfluffel** [comment]
# Tasks
- [ ] cleanup `Pan.Parser.Podcast.delta_import/1`
- [ ] cleanup `Pan.Parser.Persistor.delta_import/2`
- [ ] cleanup `Pan.Parser.Episode.persist_many/2`
